# WSL workarounds
# WSL is an interactive, non-login shell hence the need fix stuff here
if grep -qE "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  # Add missing ~/.profile stuff
  source "${HOME}/.zprofile"

  # Prevent ZSH from changing the priority of the background processes with nice.
  # https://github.com/Microsoft/WSL/issues/1887
  unsetopt BG_NICE

  # Set correct umask
  # https://github.com/Microsoft/WSL/issues/352
  [[ "$(umask)" == "000" ]] && umask 022

  # Use Docker for Windows (HyperV machine)
  export DOCKER_HOST=localhost:2375
  if ! mountpoint -q "/c"; then
    # docker-compose mounts a different path :(
    sudo mount --bind /mnt/c /c
  fi

  # Check ssh-agent config
  if [ -z "$(pgrep ssh-agent)" ]; then
    rm -rf /tmp/ssh-*
    eval $(ssh-agent -s) > /dev/null
  else
    export SSH_AGENT_PID=$(pgrep ssh-agent)
    export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name "agent.*")
  fi
  [[ "$(ssh-add -l)" == "The agent has no identities." ]] && ssh-add
fi

# Antigen plugin manager
antigen="${HOME}/.antigen.zsh"

if [ ! -f "${antigen}" ]; then
  curl -fLo "${antigen}" git.io/antigen
fi

source "${antigen}"

antigen use oh-my-zsh

antigen bundles <<EOB
archlinux
aws
common-aliases
command-not-found
docker
docker-compose
git
history
systemd
tig
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
StackExchange/blackbox
EOB

case "$TERM" in;
  *256color)
    POWERLEVEL9K_COLOR_SCHEME=light
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv vcs)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs history)
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
    POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%(!.#.$) "
    antigen theme bhilburn/powerlevel9k powerlevel9k
    ;;
esac

antigen apply

# Manual config/overrides
setopt appendhistory autocd extendedglob

export GPG_TTY=$(tty)

type kubectl > /dev/null && source <(kubectl completion zsh)
type helm > /dev/null && source <(helm completion zsh)

alias kubectl-ares='kubectl --context ares'
alias helm-ares='helm --kube-context ares'
alias kubevault-ares='kubevault --context ares --namespace devops-tools vault'
alias fly-sah='fly -t sah'

alias kubectl-hades='kubectl --context hades'
alias helm-hades='helm --kube-context hades'
alias kubevault-hades='kubevault --context hades --namespace devops-tools vault'

alias kubectl-aurora='kubectl --context demerzel.k8s.infra.dreyhub.net'
alias helm-aurora='helm --kube-context demerzel.k8s.infra.dreyhub.net'
alias fly-aurora='fly-v3.6 -t aurora'
