#!/bin/bash

set -e

function linkup
{
  local src=$1
  local dest=$2
  local prefix=$3

  find "${src}" -type f -not -name ".*" -printf "%P\n" | while read file; do
    newfile="${dest}/${prefix}${file}"
    echo -n "Linking ${file} to ${newfile}..."
    mkdir -p $(dirname ${newfile})
    ln -sf "${src}/${file}" "${newfile}"
    echo "Done."
  done
}

echo "This script will clobber your profile"
echo "Setting up links over known dotfiles"
echo "and adding a local script directory"
read -r -p "Are you sure you want to continue [y/N] " response

pushd $(dirname $0) > /dev/null
script_dir=$(pwd)
popd > /dev/null

case "${response}" in
  [yY][eE][sS]|[yY])
    echo "Linking dotfiles"
    linkup "${script_dir}/dotfiles" "${HOME}" "."
    echo "Linking scripts"
    linkup "${script_dir}/scripts" "${HOME}/bin"
    ;;
  *)
    echo "Aborting..."
    ;;
esac

