#!/bin/bash

set -e

echo "This script will clobber your profile"
echo "Setting up links over known dotfiles"
echo "and adding a local script directory"
read -r -p "Are you sure you want to continue [y/N] " response

pushd $(dirname $0) > /dev/null
script_dir=$(pwd)
popd > /dev/null

case "${response}" in
  [yY][eE][sS]|[yY])
    find "${script_dir}/dotfiles" -type f -printf "%P\n" | while read file; do
      dotfile="${HOME}/.${file}"
      echo -n "Linking ${file} to ${dotfile}..."
      mkdir -p $(basename ${dotfile})
      ln -sf "${script_dir}/dotfiles/${file}" "${dotfile}"
      echo "Done."
    done
    ;;
  *)
    echo "Aborting..."
    ;;
esac

